services:
  db:
    image: postgres:15-alpine
    container_name: sistema_gestion_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Guadalupe24*
      POSTGRES_DB: gestion_negocio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: